### ISSUE TITLE
Working sample client

### ISSUE THREAD

**Issue by MirzaSikander** [apazureck/odatatools#12]
Can you add to the repo the sample proxy client that you used to test your proxy generation? I have been able to generate the proxy for my odata endpoint, but running into some runtime issues. Having a working sample will help in figuring out the "diff" which is causing the problems. Thanks

**Comment by apazureck** [comment]
Hi,

I added my test project. It is in the develop branch. You can use the test service. It is also in the test folder. You need Visual Studio to build the odata service.

**Comment by apazureck** [comment]
FYI: Since last merge the test proxy is located in the master branch, too.
