### ISSUE TITLE
Enum?

### ISSUE THREAD

**Issue by iqmeta** [apazureck/odatatools#15]
Hi greate project.

I've added to Entity Model a 

 public enum Currency
    {
        USD,
        AED
    }

which is generated as

type Currency = "USD" | "AED";

but i have to add everywhere manually export to get the generated models to compile.

Kind regards.

**Comment by apazureck** [comment]
Hi,

Thanks, nice to hear you like it.

If I am not mistaken you can add it either in a modular fashion (with exports) or ambient. I am not sure, if I did it for both, the client generator and the interface generator.

If it does not work, please just do find and replace with the regex: `^type` and replace it with `export type`.

I'll have a look at it the next days.

**Comment by apazureck** [comment]
Hi @iqmeta,

I hope the last update fixed that, if not, please report this back. Hopefully it does not take that long to fix this time :)

**Comment by apazureck** [comment]
@iqmeta,

I hope it is working, I'll close it. If there are still problems let me know.
Regards
