### ISSUE TITLE
Customer Headers in VS Code

### ISSUE THREAD

**Issue by FlippieCoetser** [apazureck/odatatools#17]
How can add a customer header when using the plugin in VS Code. The **get entity interface...** option when pressing `crt + shift + p` only take the odata endpoint url. I need to add a access token to the Authorization tag in the header to read the odata endpoint.

**Comment by apazureck** [comment]
Hi,

Sadly, you can't. But I see your need. I'll implement that this week (possibly as workspace setting).

**Comment by apazureck** [comment]
Hi @FlippieCoetser,

Sorry for not implementing the feature so far. I had very limited time due to familiy issues to take care of my projects. I hope I can get it done the next weeks, but I sadly cannot promise anything right now.

**Comment by apazureck** [comment]
Hi @FlippieCoetser,

I implemented your request in Commit ae038dbd37a2e4ddf0e9c1ea3ba36074b415e432. I was not able to really test it. I am using [request](https://www.npmjs.com/package/request) for now, which allows quite a lot of customization. You can edit that in the header of the generated proxy/interface. See the [wiki](https://github.com/apazureck/odatatools/wiki) for more information.

Please check if it works for you and give me some feedback.

Cheers,

Andreas

**Comment by apazureck** [comment]
@FlippieCoetser,

I guess it works. At least my colleague had no issues so far using custom headers.

**Comment by FlippieCoetser** [comment]
@apazureck thanks for the Implementation!!!
