### ISSUE TITLE
Wrong property types

### ISSUE THREAD

**Issue by olexu** [apazureck/odatatools#26]
Receive wrong property types while creating proxy for oData service: 
 http://services.odata.org/V4/Northwind/Northwind.svc/$metadata
**[object Object]**
`namespace NorthwindModel {

    export interface Category {
        CategoryID: [object Object];
        CategoryName: [object Object];
        Description: [object Object];
        Picture: [object Object];
        Products?: [object Object];

    }`

**Comment by apazureck** [comment]
Hi,

Shoot, I forgot to copy the template to the distribution folder. Sorry for that. Please replace the file content of proxy.ot with the following. There the errors should be fixed:

https://github.com/apazureck/odatatools/blob/develop/test/testproject/.vscode/odatatools/templates/proxy.ot

I'll upload a patch tomorrow. Let me know if this fixed your issue.

**Comment by olexu** [comment]
Thanks, it works
