### ISSUE TITLE
Collection types are not correctly converted to arrays

### ISSUE THREAD

**Issue by olexu** [apazureck/odatatools#27]
Checked with http://services.odata.org/V4/Northwind/Northwind.svc/$metadata

Entity Category has a NavigationProperty **Products** with type **Collection(NorthwindModel.Product)**
`
<EntityType Name="Category">
<Key>
<PropertyRef Name="CategoryID"/>
</Key>
<Property xmlns:p5="http://schemas.microsoft.com/ado/2009/02/edm/annotation" Name="CategoryID" Type="Edm.Int32" Nullable="false" p5:StoreGeneratedPattern="Identity"/>
<Property Name="CategoryName" Type="Edm.String" Nullable="false" MaxLength="15"/>
<Property Name="Description" Type="Edm.String" MaxLength="max"/>
<Property Name="Picture" Type="Edm.Binary" MaxLength="max"/>
<NavigationProperty Name="Products" Type="Collection(NorthwindModel.Product)" Partner="Category"/>
</EntityType>
`

But it is converted as Products?: **NorthwindModel.Product** not Products?: **Array<NorthwindModel.Product>**

`
export interface Category {
        CategoryID: Edm.Int32;
        CategoryName: Edm.String;
        Description: Edm.String;
        Picture: Edm.Binary;
        Products?: NorthwindModel.Product;}
`

**Comment by apazureck** [comment]
Updated template:
https://github.com/apazureck/odatatools/blob/develop/test/testproject/.vscode/odatatools/templates/proxy.ot
It should work now for all types. Thanks for reporting.
