### ISSUE TITLE
Creating Proxi Error: Cann not read property 'match' of undefiend

### ISSUE THREAD

**Issue by kueblertgb** [apazureck/odatatools#41]
HI i tryed to create a proxy with your tool 
i tryed it with the URI: https://services.odata.org/V2/Northwind/Northwind.svc

I got this errors:
[INFO ] extension: Extension "odatatools" is now active!
[INFO ] extension: Using Extension Version: 2.0
[INFO ] extension: Insider mode active: No
[INFO ] v200commands: Getting Metadata from 'https://services.odata.org/V2/Northwind/Northwind.svc/$metadata'
[ERROR] Creating proxy returned following error:
[ERROR] TypeError: Cannot read property 'match' of undefined
[INFO ] v200commands: Updating current file.

Can you help me?

**Comment by apazureck** [comment]
Hi,

This Client Generator is for OData V4. In your URL I can see you are trying to read the metadata from the Northwind V2 Service.

Please try the V4:

https://services.odata.org/V4/Northwind/Northwind.svc/$metadata

and it should work. I tried it with the V4 Service and it worked for me.

You can generate the client and than edit the outcoming proxy to your liking.

If you need Odata V2 feel free to fork the repo. PRs are welcome

Even though I have not been very active on this project for quite a time it is still maintained.

**Comment by apazureck** [comment]
Hi, did it help you? Can I close it?
